apiVersion: v1
kind: ConfigMap
metadata:
  name: whiskey-analytics-configmap
  namespace: whiskey-analytics
  labels:
    app: redis
data:
  config.ini: |
    [base]
    log_level = "INFO"

    [api]
    url = "https://whiskyhunter.net/api/auctions_data"
    output = "json"
    parse_date_column = "dt"

    [sink]
    mode = "overwrite"
    table_name = "whiskey_bidding"
    table_base_uri = "s3://lakehouse-local/lakehouse/bronze"
    overwrite_schema = True

    [delta]
    endpoint_url = "http://minio-svc.whiskey-analytics.svc.cluster.local:9000"
    aws_s3_allow_unsafe_rename = "1"
