apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: whiskey-extractor
  name: whiskey-extractor
  namespace: whiskey-analytics
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: whiskey-extractor
        spec:
          serviceAccountName: whiskey-service-account
          containers:
          - name: whiskey-extractor
            image: datapains/whiskey-extractor:0.0.1
            command: [ "make" ]
            args: ["--directory", "/app/", "run", "config-file-name=/app/config/config.ini"]
            imagePullPolicy: Never
            resources:
              limits:
                memory: "1Gi"
                cpu: "1"
              requests:
                memory: "1Gi"
                cpu: "1"
            volumeMounts:
              - name: whiskey-analytics-configmap
                mountPath: /app/config
            env:
              - name: AWS_SECRET_ACCESS_KEY
                value: "accountadmin123"
              - name: AWS_ACCESS_KEY_ID
                value: "accountadminsecret123"
              - name: AWS_REGION
                value: "us-west-1"
          volumes:
            - name: whiskey-analytics-configmap
              configMap:
                name: "whiskey-analytics-configmap"
                defaultMode: 0777
                items:
                  - key: "config.ini"
                    path: "config.ini"
          restartPolicy: OnFailure
