apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
  namespace: whiskey-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: whiskey-service-account
      containers:
      - name: app
        image: datapains/whiskey-extractor:0.0.1
        command: [ "make" ]
        args: ["--directory", "/app/", "run", "config-file-name=/app/config/config.ini"]
        imagePullPolicy: Never
        resources:
          limits:
            memory: 2Gi
            cpu: "2"
          requests:
            memory: 2Gi
            cpu: "1"
        volumeMounts:
          - name: whiskey-analytics-configmap
            mountPath: /app/config
        env:
          - name: AWS_SECRET_ACCESS_KEY
            value: "accountadmin123"
          - name: AWS_ACCESS_KEY_ID
            value: "accountadminsecret123"
          - name: AWS_REGION
            value: "us-west-1"
      volumes:
        - name: whiskey-analytics-configmap
          configMap:
            name: "whiskey-analytics-configmap"
            defaultMode: 0777
            items:
              - key: "config.ini"
                path: "config.ini"